export const START_POSTS = "START_REQUEST_POSTS";
export const REQUEST_POSTS = "REQUEST_POSTS";
export const REQUEST_POSTS_SUCCESS = "REQUEST_POSTS_SUCCESS";
export const REQUEST_POSTS_FAILED = 'REQUEST_POSTS_FAILED'

export const START_COMMENTS_BY_POST = "START_REQUEST_COMMENTS_BY_POST";
export const REQUEST_COMMENTS = "REQUEST_COMMENTS";
export const REQUEST_COMMENTS_SUCCESS = "REQUEST_COMMENTS_SUCCESS"
export const REQUEST_COMMENTS_FAILED = "REQUEST_COMMENTS_FAILED"

export const START_USER_OF_POST = "START_REQUEST_USER_OF_POST";
export const REQUEST_USER_OF_POST = "REQUEST_USER_OF_POST";
export const REQUEST_USER_OF_POST_SUCCESS = "REQUEST_USER_OF_POST_SUCCESS";
export const REQUEST_USER_OF_POST_FAILED = "REQUEST_USER_OF_POST_FAILED";

export const START_USERS_POSTS = "START_USERS_POSTS";
export const REQUEST_USER_POSTS = "REQUEST_USER_POSTS";
export const REQUEST_USER_POSTS_SUCCESS = "REQUEST_USER_POSTS_SUCCESS";
export const REQUEST_USER_POSTS_FAILED = "REQUEST_USER_POSTS_FAILED";