export const GET_POSTS = "GET_POSTS";
export const REQUEST_POSTS = "REQUEST_POSTS";
export const POSTS_FAILED = 'POSTS_FAILED'


export const REQUEST_COMMENTS = "REQUEST_COMMENTS";
export const GET_COMMENTS_BY_POST = "GET_COMMENTS_BY_POST"


export const SHOW_LOADER = "SHOW_LOADER"
export const HIDE_LOADER     = "HIDE_LOADER"