export const REQUEST_POSTS = "REQUEST_POSTS";
export const REQUEST_POSTS_SUCCESS = "REQUEST_POSTS_SUCCESS";
export const REQUEST_POSTS_FAILED = 'REQUEST_POSTS_FAILED'

export const REQUEST_COMMENTS = "REQUEST_COMMENTS";
export const REQUEST_COMMENTS_SUCCESS = "REQUEST_COMMENTS_SUCCESS"
export const REQUEST_COMMENTS_FAILED = "REQUEST_COMMENTS_FAILED"

export const REQUEST_USER_OF_POST = "REQUEST_USER_OF_POST";
export const REQUEST_USER_OF_POST_SUCCESS = "REQUEST_USER_OF_POST_SUCCESS";
export const REQUEST_USER_OF_POST_FAILED = "REQUEST_USER_OF_POST_FAILED";